require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/courses", type: :request do
  
  let(:user) { create(:user) }
  
  before(:each){
    sign_in_user user
  }

  describe "GET /index" do
    it "renders a successful response" do
      course = create(:course)
      create_list(:course, 3)
      get school_courses_url(course.school)
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      course = create(:course)
      get school_course_url(course.school, course)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      course = create(:course)
      get new_school_course_url(course.school)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      course = create(:course)
      get edit_school_course_url(course.school, course)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Course" do
        school = create(:school)
        course_params = attributes_for(:course, school: school)
        expect {
          post school_courses_url(school), params: { course: course_params }
        }.to change(Course, :count).by(1)
      end

      it "redirects to the created course" do
        school = create(:school)
        course_params = attributes_for(:course, school: school)
        post school_courses_url(school), params: { course: course_params }
        expect(response).to redirect_to(school_course_url(school, Course.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Course" do
        school = create(:school)
        course_params = attributes_for(:course, :invalid)
        expect {
          post school_courses_url(school), params: { course: course_params }
        }.to change(Course, :count).by(0)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {name: "Course 1"}
      }

      it "updates the requested course" do
        course = create(:course)
        patch school_course_url(course.school, course), params: { course: new_attributes }
        course.reload
        expect(course.name).to eql("Course 1")
      end

      it "redirects to the course" do
        course = create(:course)
        patch school_course_url(course.school, course), params: { course: new_attributes }
        course.reload
        expect(response).to redirect_to(school_course_url(course.school, course))
      end
    end

    context "with invalid parameters" do
      it "does not update course" do
        course = create(:course)
        course_params = attributes_for(:course, :invalid)
        patch school_course_url(course.school, course), params: { course: course_params }
        expect(response).to have_http_status(:unprocessable_entity)
        course.reload
        expect(course.name).not_to be_empty
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested course" do
      course = create(:course)
      expect {
        delete school_course_url(course.school, course)
      }.to change(Course, :count).by(-1)
    end

    it "redirects to the courses list" do
      course = create(:course)
      delete school_course_url(course.school, course)
      expect(response).to redirect_to(school_courses_url(course.school))
    end
  end
end
