require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/school_admins", type: :request do
  
  let(:user) { create(:user) }
  
  before(:each){
    sign_in_user user
  }

  describe "GET /index" do
    it "renders a successful response" do
      school_admin = create(:school_admin)
      create_list(:school_admin, 3)
      get school_school_admins_url(school_admin.school)
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      school_admin = create(:school_admin)
      get school_school_admin_url(school_admin.school, school_admin)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      school_admin = create(:school_admin)
      get new_school_school_admin_url(school_admin.school)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      school_admin = create(:school_admin)
      get edit_school_school_admin_url(school_admin.school, school_admin)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SchoolAdmin" do
        school = create(:school)
        school_admin_params = attributes_for(:school_admin, school: school)
        expect {
          post school_school_admins_url(school), params: { school_admin: school_admin_params }
        }.to change(SchoolAdmin, :count).by(1)
      end

      it "redirects to the created school_admin" do
        school = create(:school)
        school_admin_params = attributes_for(:school_admin, school: school)
        post school_school_admins_url(school), params: { school_admin: school_admin_params }
        expect(response).to redirect_to(school_school_admin_url(school, SchoolAdmin.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SchoolAdmin" do
        school = create(:school)
        school_admin_params = attributes_for(:school_admin, :invalid)
        expect {
          post school_school_admins_url(school), params: { school_admin: school_admin_params }
        }.to change(SchoolAdmin, :count).by(0)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {name: "School Admin 1"}
      }

      it "updates the requested school_admin" do
        school_admin = create(:school_admin)
        patch school_school_admin_url(school_admin.school, school_admin), params: { school_admin: new_attributes }
        school_admin.reload
        expect(school_admin.name).to eql("School Admin 1")
      end

      it "redirects to the school_admin" do
        school_admin = create(:school_admin)
        patch school_school_admin_url(school_admin.school, school_admin), params: { school_admin: new_attributes }
        school_admin.reload
        expect(response).to redirect_to(school_school_admin_url(school_admin.school, school_admin))
      end
    end

    context "with invalid parameters" do
      it "doesnot update school admin" do
        school_admin = create(:school_admin)
        school_admin_params = attributes_for(:school_admin, :invalid)
        patch school_school_admin_url(school_admin.school, school_admin), params: { school_admin: school_admin_params }
        expect(response).to have_http_status(:unprocessable_entity)
        school_admin.reload
        expect(school_admin.email).not_to be_empty
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested school_admin" do
      school_admin = create(:school_admin)
      expect {
        delete school_school_admin_url(school_admin.school, school_admin)
      }.to change(SchoolAdmin, :count).by(-1)
    end

    it "redirects to the school_admins list" do
      school_admin = create(:school_admin)
      delete school_school_admin_url(school_admin.school, school_admin)
      expect(response).to redirect_to(school_school_admins_url)
    end
  end
end
